# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [39]:
# memory size 는 다음 공식을 따른다.

x = np.array([100,20,34])

print("Size of the array: ",
      x.size)

print("Memory size of one array element in bytes: ",
      x.itemsize)

# memory size of numpy array in bytes
print("Memory size of numpy array in bytes:",
      x.size * x.itemsize)


Size of the array:  3
Memory size of one array element in bytes:  4
Memory size of numpy array in bytes: 12


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
# np.00 하면 되지 않나?
print(np.info(np.add))

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [41]:
x = np.arange(10, 50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [44]:
print(x[::-1])
x=np.sort(x)[::-1]
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
x = np.arange(0, 9)
y=x.reshape(3,3)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [68]:
x = np.array([1,2,0,0,4,0])
# for i in range(len(vector)):
#     if vector[i] != 0:
#         print(i)
# or

print(np.argwhere(x !=0))

[[0]
 [1]
 [4]]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [32]:
x = np.array([[ 1,  0,  0], [ 0,  1,  0],[ 0,  0,  1]])
print(x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [34]:
# .random.random
x = np.random.random((3,3,3))
print(x)

[[[0.01131528 0.45869746 0.04671711]
  [0.40743269 0.59713217 0.53951508]
  [0.67465594 0.44362812 0.06750801]]

 [[0.2919084  0.68859486 0.38335852]
  [0.05833984 0.44474101 0.61812686]
  [0.41620158 0.16193113 0.70434027]]

 [[0.23553747 0.06047848 0.11201859]
  [0.57123461 0.2494496  0.45742456]
  [0.97812073 0.59386329 0.17566267]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [46]:
x = np.random.random((10, 10))
print(x)
np.min(x)
np.max(x)

[[0.64994335 0.88115175 0.59772098 0.78539645 0.2949002  0.05588964
  0.55908118 0.16243362 0.77631843 0.82469517]
 [0.00509458 0.79064773 0.60022943 0.80835557 0.48460713 0.09762926
  0.60315788 0.15854149 0.6656295  0.11019327]
 [0.37316819 0.8971133  0.64933531 0.25016557 0.27404112 0.51443522
  0.83242076 0.84986481 0.91710007 0.9160681 ]
 [0.94802976 0.56505223 0.52611387 0.40136004 0.95280463 0.43479134
  0.23960855 0.18696813 0.79747548 0.75671591]
 [0.19023585 0.70836775 0.16471649 0.33791349 0.45386707 0.23367279
  0.22440113 0.63641312 0.61032848 0.24108085]
 [0.24795271 0.06075176 0.27233815 0.29452544 0.67973902 0.94075947
  0.6169484  0.07323997 0.85797023 0.02886405]
 [0.00489351 0.80912322 0.37742009 0.92670707 0.60448714 0.33199058
  0.89740136 0.42371123 0.45318568 0.32415955]
 [0.30055251 0.23148241 0.82982718 0.81644911 0.60225995 0.56496178
  0.66171113 0.47971174 0.32757945 0.63458378]
 [0.95625833 0.98640883 0.44949247 0.2151933  0.46056713 0.78686973
  0.35173486

0.9864088326630595

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [50]:
x = np.random.random((30))
print(x)
np.mean(x)

[0.25258893 0.86338496 0.25876344 0.30170149 0.19332356 0.36331096
 0.72539541 0.52411104 0.82792443 0.85394143 0.21205201 0.01488932
 0.93564437 0.41088629 0.99699908 0.0643153  0.41702756 0.78750489
 0.41372273 0.56467218 0.00871408 0.18564143 0.60471955 0.88615655
 0.32989049 0.07312088 0.89960946 0.95205723 0.59626792 0.34359012]


0.49539756902695586

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [58]:
x = np.ones((4, 4))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [60]:
# np.pad() 함수

x = np.ones((4, 4))
y = np.pad(array=x, pad_width=1, mode='constant')

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
# np.nan(), np.inf() 함수
0 * np.nan           # nan
np.nan == np.nan     # False
np.inf > np.nan      # False
np.nan - np.nan      # nan
0.3 == 3 * 0.1       # False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
# np. diag() 함수

x = np.array([1, 2, 3, 4])
np.diag(x)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [61]:
x = np.zeros((8, 8))
x[1::2, ::2] = 1
x[::2, 1::2] = 1

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [62]:
# np.unravel_index()

np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
# np.tile() 함수

np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [51]:
# 여기부터

import numpy as np
x= np.random.random((5,5))
xmax = x.max()
xmin = x.min()
x = (x - xmin)/(xmax - xmin)
print(x)

[[0.5030962  0.68410446 0.46743783 0.136232   0.        ]
 [0.60828143 0.77679572 0.60790333 0.08219859 0.89597781]
 [0.51454055 0.28392058 0.69729236 0.17696915 1.        ]
 [0.36076474 0.02625366 0.19439999 0.81768437 0.51935318]
 [0.82123569 0.28255593 0.19204201 0.9893852  0.23490572]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [53]:
#np.dtype

data = np.dtype([("r",np.ubyte, 1),("g",np.ubyte, 1),("b",np.ubyte, 1),("a",np.ubyte, 1)])
print(data)


[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [54]:
# np.dot () 사용

x = np.random.random((5,3))
y = np.random.random((3,2))
multiply = np.dot(x, y)
print(multiply)


[[0.829052   0.5796845 ]
 [0.50122592 0.74353099]
 [0.73855277 0.71728787]
 [0.86329772 0.80121672]
 [1.0963575  0.6902439 ]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [56]:
x = np.arange(10)
x[(3<= x) & (x<=8)] = -1
print(x)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [63]:
print(sum(range(5), -1))  # 9
from numpy import *

print(sum(range(5), -1))  # 10

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [64]:
Z = np.arange(3)
Z ** Z       # = [0^0, 1^1, 2^2] = [1, 1, 4]
2 << Z >> 2  # = [0, 1, 2]
Z < - Z      # = [False, False, False]
1j * Z       # = [0 + 0.j, 0 + 1.j, 0 + 2.j]
Z / 1 / 1    # = [0, 1, 2]
Z < Z > Z    # ValueError

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [65]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
# np.copysign() 함수

x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
# np.intersect1d() 함수

x = np.arange(0, 10)
y = np.arange(5, 15)
np.intersect1d(x, y)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [66]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [67]:
# np.emath.sqrt() 함수

print(np.sqrt(-1) == np.emath.sqrt(-1))  # False

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
# np. datetime64()

today = np.datetime64('today', 'D')
yesterday = today - np.datetime64(1, 'D')
tomorrow = today + np.datetime64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)