# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [14]:
import numpy as np
data = np.arange('2016-07','2016-08', dtype='datetime64[D]')
print(data)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [15]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [16]:
x = np.random.uniform(-10, +10, 10)
x.astype(np.int32)
np.trunc(x)

array([ 4.,  2., -8., -5., -1.,  1., -2., -8., -2.,  7.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [19]:
data = np.zeros((5,5))
data += np.arange(5)
print(data)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [20]:
def generate_integers():
    for i in range(10):
        yield i
np.fromiter(generate_integers(), dtype=np.float32, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [21]:
np.linspace(start=0, stop=11, num=10, endpoint=False)

array([0. , 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [24]:
x = np.random.random(size=10)
x.sort()
print(x)

[0.02850345 0.07818469 0.24369036 0.36856617 0.44717352 0.5837625
 0.65662022 0.80809359 0.83449615 0.9864862 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [25]:
import time

begin_time = time.time()
x = np.arange(1000000)
np.sum(x)
end_time = time.time()
print(str(1000*(end_time - begin_time)))

begin_time2 = time.time()
x = np.arange(1000000)
np.add.reduce(x)
end_time2 = time.time()
print(str(1000*(end_time2 - begin_time2)))

3.99017333984375
3.9892196655273438


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [26]:
A = np.arange(10)
B = np.arange(10)
np.array_equal(A, B)

True

#### 43. Make an array immutable (read-only) (★★☆)

In [28]:
data = np.zeros(10)
data.flags.writeable= False
data[0]=1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [29]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.29104382 1.0609464  0.77326574 0.96943387 0.56505016 0.96020592
 0.97681104 0.88096745 0.77970976 1.24570378]
[1.20991925 0.75296153 0.46698213 0.54705589 0.07423491 1.09029266
 0.54427166 0.41934725 0.93682194 0.6791674 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [30]:
x = np.random.random(10)
x[x == np.max(x)] = 0
x[x.argmax()] = 0

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [31]:
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [32]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / (x - y)
c = 1 / np.subtract.outer(x, y)
np.linalg.det(c)

array([[ 8.57712305e+06,  1.52027704e+05,  8.88821536e+05,
        -1.83305942e+06,  5.35386671e+05],
       [ 9.93937363e+04,  1.98632023e+05, -1.15410031e+05,
         2.75046194e+03, -3.48996913e+04],
       [ 2.71143504e+03, -3.99243751e+02,  1.82249441e+07,
        -4.47383849e+06,  1.39075755e+05],
       [ 1.19489739e+06, -6.07870257e+07,  9.56840889e+04,
         4.10337769e+03, -3.24982350e+04],
       [ 1.03422069e+05,  3.04360116e+03, -2.49817126e+05,
         1.94683853e+05, -5.45264384e+06]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [33]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [35]:
np.set_printoptions(threshold=np.nan)

ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [38]:
data = np.arange(100)
print(data)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(data - v)).argmin()
print(data[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
74.46191667010082
74


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [39]:
position = ('position', [ ('x', float, 1),('y', float, 1)])
color = ('color', [('r', float), ('g', float), ('b', float)])
data = np.zeros(10,[position, color])
print(data)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  This is separate from the ipykernel package so we can avoid doing imports until


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [43]:
data = np.random.random((10,2))
print(data)
X, Y = np.atleast_2d(data[:, 0], data[:, 1])
print(X,'----',y)
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)
print('-'*10)
import scipy
import scipy.spatial
data = np.random.random((10,2))
print(data)
D = scipy.spatial.distance.cdist(data,data)
print(D)

[[0.24875244 0.67944383]
 [0.25666214 0.27976562]
 [0.32696835 0.64885136]
 [0.62705314 0.46099905]
 [0.00733177 0.01505183]
 [0.95226566 0.45253204]
 [0.01772401 0.53994671]
 [0.00459338 0.4157949 ]
 [0.11753532 0.6657576 ]
 [0.87973417 0.8792048 ]]
[[0.24875244 0.25666214 0.32696835 0.62705314 0.00733177 0.95226566
  0.01772401 0.00459338 0.11753532 0.87973417]] ---- [[0.33719949 0.14655201 0.9051524  0.78569292 0.60820486]
 [0.79696611 0.13419462 0.01330447 0.49108735 0.25083406]
 [0.14261698 0.55886675 0.60109178 0.67183704 0.34849283]
 [0.5896754  0.20261139 0.14714424 0.43152951 0.23631115]
 [0.58163844 0.20593391 0.04597285 0.72743136 0.10585517]]
[[0.         0.39975647 0.08398588 0.43684041 0.70689509 0.73920215
  0.26987697 0.35933884 0.13192894 0.66184771]
 [0.39975647 0.         0.37572231 0.41235307 0.36364683 0.71673739
  0.3532501  0.28643084 0.41029999 0.86460748]
 [0.08398588 0.37572231 0.         0.35403301 0.70983758 0.65539148
  0.32786016 0.3977951  0.21011429 0.59

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [44]:
data = np.arange(10, dtype = np.float32)
data = data.astype(np.int32, copy = False)
print(data)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [45]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n 6, , , 7, 8\n , , 9,10,11\n""")
data = np.genfromtxt(s, delimiter=",", dtype =np.int)
print(data)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [46]:
Z = np.arange(9).reshape(3,3)
print(Z)
for idx, val in np.ndenumerate(Z):
    print(idx, val)
for idx in np.ndindex(Z.shape):
    print(idx, Z[idx])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [49]:
X,Y = np.meshgrid(np.linspace(-1,1, 10) , np.linspace(-1,1,10))
print(X,Y)
D = np.sqrt(X*X+ Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu) ** 2 / (2.0 * sigma**2)))
print(G)

[[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [51]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p , replace= False),1)
print(Z)
print(np.random.choice(range(n*n), p))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[19 78 37]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [53]:
X = np.random.rand(5,10)
print(X)
Y = X - X.mean(axis = 1, keepdims = True)
print(Y)
Y = X - X.mean(axis=1).reshape(-1,1)
print(Y)

[[0.05404847 0.9257326  0.13623747 0.05143688 0.95763995 0.69391903
  0.17884909 0.06410484 0.48451861 0.93646143]
 [0.64023808 0.32744722 0.70130834 0.42782094 0.66924488 0.81458286
  0.27196229 0.76624838 0.08932612 0.75001142]
 [0.51813254 0.9614387  0.19196503 0.06274354 0.22716365 0.28446226
  0.85356884 0.69773772 0.8703551  0.66917976]
 [0.49103181 0.39621477 0.15644282 0.35418055 0.09588538 0.99775695
  0.24539176 0.47292452 0.92098391 0.94956088]
 [0.57099357 0.45306289 0.71185056 0.55001185 0.96834185 0.66276648
  0.6526024  0.53681145 0.47662305 0.45164547]]
[[-0.39424637  0.47743776 -0.31205737 -0.39685796  0.50934511  0.24562419
  -0.26944575 -0.38418999  0.03622377  0.48816659]
 [ 0.09441903 -0.21837183  0.15548929 -0.11799812  0.12342583  0.2687638
  -0.27385676  0.22042933 -0.45649294  0.20419236]
 [-0.01554218  0.42776398 -0.34170968 -0.47093118 -0.30651106 -0.24921245
   0.31989412  0.16406301  0.33668039  0.13550505]
 [-0.01700553 -0.11182256 -0.35159452 -0.15385679 

#### 59. How to sort an array by the nth column? (★★☆)

In [54]:
data = np.random.randint(0,10,(3,3))
print(data)
print(data[data[:,1].argsort()])

[[2 6 5]
 [9 0 1]
 [5 8 2]]
[[9 0 1]
 [2 6 5]
 [5 8 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [55]:
data = np.random.randint(0,10,(3,3))
print((~data.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [58]:
data = np.random.uniform(0,1,10)
print(data)
z = 0.5
print(np.abs(data-z))
print(np.abs(data-z).argmin())
m = data.flat[np.abs(data-z).argmin()]
print(m)

[0.00651765 0.28536599 0.74120625 0.2225963  0.88076757 0.07296534
 0.53322303 0.5091635  0.49344751 0.21306101]
[0.49348235 0.21463401 0.24120625 0.2774037  0.38076757 0.42703466
 0.03322303 0.0091635  0.00655249 0.28693899]
8
0.4934475111988952


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [59]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
print(A, B)
it = np.nditer([A,B, None])
for x,y,z in it:
    z[...] = x+y
print(it.operands[2])

[[0]
 [1]
 [2]] [[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [60]:
class NameArray(np.ndarray):
    def __new__(cls, array, name ="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.info = getattr(obj,'name','no name')
data = NameArray(np.arange(10),'range_10')
print(data.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [62]:
data = np.ones(10)
I = np.random.randint(0, len(Z), 20)
print(I)
data += np.bincount(I, minlength = len(Z))
print(data)
np.add.at(data,I,1)
print(data)

[8 8 9 9 1 2 3 2 0 3 7 7 0 7 0 2 7 7 9 1]
[4. 3. 4. 3. 1. 1. 1. 6. 3. 4.]
[ 7.  5.  7.  5.  1.  1.  1. 11.  5.  7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [63]:
A = [1,2,3,4,5,6]
B = [1,3,9,3,4,1]
C = np.bincount(B,A)
print(C)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [64]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]* 256 + I[...,2]
n = len(np.unique(F))
print(n)
print(np.unique(I))

8
[0 1]
