In [ ]:
사이킷런으로 시작하는 머신러닝
1. 사이킷런 소개와 특징

In [2]:
import sklearn
print(sklearn.__version__)

0.24.2


In [ ]:
2. 첫 번째 머신러닝 만들어 보기 - 붓꽃 품종 예측하기

- 붓꽃 data set : 꽃잎의 길이, 너비, 꽃받침의 길이, 너비
- 분류는 대표적인 지도학습 방법의 하나이다.
- 지도학습은 학습을 위한 다양한 피처와 분류 결정값인 레이블 데이터로 모델을 학습한 뒤, 별도의 테스트 데이터 세트에서 미지의 레이블을 예측한다.
- 학습 데이터 세트 : 학습을 위해 주어진 데이터 세트
- 테스트 데이터 세트 : 머신러닝 모델의 예측 성능을 평가하기 위해 별도로 주어진 데이터 세트
- 사이킷런 패키지 내 모듈명은 sklearn 으로 시작하는 명명규칙이 있다.
- sklearn.tree 모듈 : 트리 기반 ml 알고리즘을 구현한 클래스의 모임
- sklearn.medel_selection : 학습 데이터와 검증 데이터, 예츨 데이터로 데이터를 분리하거나 최적의 하이퍼 파라미터로 평가하기 위한 모듈의 모임.
- 하이퍼 파라미터 : 머신러닝 알고리즘별로 최적의 학습을 위해 직접 입력하는 파라미터들. 이를 통해 머신러닝 성능을 튜닝할 수 있다.

In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

- load_iris() : 붓꽃 데이터 세트를 생성

In [5]:
import pandas as pd

# 붓꽃 데이터 세트를 로딩한다.
iris = load_iris()

# iris.data 는 Iris 데이터 세트에서 피처(feature)만으로 된 데이터를 numpy로 가지고 있습니다.
iris_data = iris.data

# iris.target 은 붓꽃 데이터 세트에서 레이블(결정 값) 데이터를 numpy로 가지고 있습니다.
iris_label = iris.target #setosa, vesicolor, virginica 3 종류가 있고, 각각 0,1,2 로 되어 있다는 뜻.
print('iris target값 :', iris_label)
print('iris target명 :', iris.target_names)

# 붓꽃 데이터 세트를 자세히 보기 위해 DataFrame 으로 변환합니다.
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df

iris target값 : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명 : ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

<학습용 데이터와 테스트용 데이터 분리>
- 학습용 데이터와 테스트용 데이터는 반드시 분리해야 함.
- train_test_split() : 학습 데이터와 테스트 데이터를 test_size 파라미터 입력 값의 비율로 쉽게 분할한다. ex) test_size=0.2 로 하면, 전체 데이터 중 테스트 데이터가 20%, 학습 데이터가 80%로 데이터를 분할한다.

In [9]:
# 학습용 데이터와 테스트용 데이터 분리
# 학습용 피처 데이터 세트를 X_train 이고, 테스트 용 피처 데이터 세트를 X_test로, 학습용 레이블 데이터 세트를 y_train으로, 테스트용 레이블 데이터 세트를 y_test 로 반환
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

- train_test_split() 의 첫 번째 파라미터 인, iris_data 는 피처 데이터 세트.
- 두 번째 파라미터 iris_label 은 레이블 데이터 세트
- 전체 데이터 세트 중 테스트 데이터 세트의 비율
- random_state 는 호출할 때 마다 같은 학습/테스트 용 데이터 세트를 생성하기 위해 주어진 난수 발생 값. ==> 지정하지 않으면 수행할 때 마다 다른 학습/ 테스트 용 데이터를 만듦. (숫자는 뭐든 상관 없음)

In [10]:
# DecisionTreeClassifier(사이킷런의 의사 결정 트리 클래스) 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

- 생성된 DecisionTreeClassifier 객체의 fit() 메서드에 학습용 피처 데이터 속성과 결정값 데이터 세트를 입력해 호출하면 학습을 수행한다.
- 아래의 코드가 수행되면 : 의사 결정 트리 기반의 DecisionTreeClassifier 객체는 학습 데이터를 기반으로 학습이 완료 ==> 이를 기반으로 예측 수행 가능. 예측은 반드시 학습 데이터가 아닌 다른 데이터를 이용해야 함. 일반적으로 테스트 데이터 세트를 이용

In [11]:
# 모델 학습
# 학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

- DecisonTreeClassifier 객체의 predict() 메서드에 테스트용 피처 데이터 세트를 입력해 호출하면 학습된 모델 기반에서 데스트 데이터 세트에 대한 예측값을 반환

In [12]:
# 예측 수행
# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행.
pred = dt_clf.predict(X_test)

- 예측 결과를 기반으로 의사결정트리 기반의 DecisionTreeClassifier의 예측 성능을 평가.
- 일반적으로 머신러닝 모델의 성능 평가 방법은 여러가지가 있다.
- 아래에선 정확도를 측정해보겠다.
- 정확도 : 예측 결과가 실제 레이블 값과 얼마나 정확하게 맞는지를 평가하는 지표
- accuracy_score() : 사이킷런의 정확도 측정 함수
- accuracy_score 의 첫 번째 파라미터는 실제 레이블 데이터 세트, 두 번째 파라미터로 예측 레이블 데이터 세트 입력

In [13]:
# 정확도 측정
from sklearn.metrics import accuracy_score
print('예측 정확도 : {0:4f}'.format(accuracy_score(y_test,pred)))

예측 정확도 : 0.933333


<붓꽃 데이터 분류 예측 프로세스>
1. 데이터 세트 분리 : 데이터를 학습 데이터와 테스트 데이터로 분리
2. 모델 학습 : 학습 데이터를 기반으로 ML 알고리즘을 적용해 모델을 학습시킴
3. 예측 수행 : 학습된 ML 모델을 이용해 테스트 데이터의 분류(붓꽃 종류) 를 예측한다.
4. 평가 : 이렇게 예측된 결괏값과 테스트 데이터의 실제 결괏값을 비교해 ML 모델 성능을 평가

In [ ]:
3. 사이킷런의 기반 프레임워크 익히기

- 사이킷런은 ML 모델 학습을 위해 : fit() 을
- 학습된 모델의 예측을 위해 : predict() 매서드를 제공.
- 지도 학습의 주요 두 축인 분류와 회귀의 다양한 알고리즘을 구현한 모든 사이킷런 클래스는 fit()과 predict() 만을 이용해 간단하게 학습과 예측 결과를 반환
- 분류 알고리즘을 구현한 클래스 : Classifier로,
- 회귀 알고리즘을 구현한 클래스 : Regressor 로 지칭
- Estimator : Classifier 과 Regaressor 을 합침 (당연히 내부에서 fit(), predict() 구현)

<사이킷런의 주요 모듈>
1. 예제 데이터
1) sklearn.datasets : 사이킷런에 내장되어 예제로 제공하는 데이터 세트
2. 피처 처리
1) sklearn.preprocessing : 데이터 전처리에 필요한 다양한 가공 기능 제공 (문자열을 숫자형 코드 값으로 인코딩, 정규화, 스케일링 등)
2) sklearn.feature_selection : 알고리즘에 큰 영향을 미치는 피처를 우선순위대로 셀렉션 작업을 수행하는 다양한 기능 제공
3) sklearn.feature_extraction : 텍스트 데이터나 이미지 데이터의 벡터화된 피처를 추출하는데 사용됨.
3. 피처 처리 & 차원 축소
1) sklearn.decomposition : 차원 축소와 관련한 알고리즘을 지원하는 모듈.
4. 데이터 분리, 검증&파라미터 튜닝
1) sklearn.model_selection : 교차 검증을 위한 학습용/테스트용 분리
5. 평가
1) sklearn.metrics : 분류, 회귀, 클러스터링, 페어와이즈에 대한 다양한 성능 측정 방법 제공
6. ML 알고리즘
1) sklearn.ensemble : 앙상블 알고리즘 제공
2) sklearn.linear_model : 주로 선형회귀, 릿지, 라쏘 및 로지스틱 회귀 등 회귀 관련 알고리즘을 지원
3) sklearn.naive_bayes : 나이브 베이즈 알고리즘 제공. 가우시안, NB, 다항분포 등
4) sklearn.neighbors : 최근접 이웃 알고리즘 제공
5) sklearn.svm : 서포트 벡터 머신 알고리즘 제공
6) sklearn.tree : 의사 결정 트리 알고리즘 제공
7) sklearn.cluster : 비지도 클러스터링 알고리즘 제공
7. 유틸리티
1) sklearn.pipline : 피처 처리 등의 변환과 ML 알고리즘 학습, 예측등을 함께 묶어 실행가능한 유틸리티 제공

일반적으로 머신러닝 모델을 구축하는 주요 프로세스는 피처의 가공, 변경, 추출을 수행하는 피처 처리, ML 알고리즘 학습/ 예측 수행, 그리고 모델 평가의 단계를 반복적으로 수행하는 것

<내장된 예제 데이터 세트>
두가지로 나뉨. 대부분 일반적으로 '딕셔너리' 형태로 저장되이 있음.
1. 분류나 회귀를 연습하기 위한 예제 용도
2. 분류나 클러스터링을 위해 표본 데이터로 생성될 수 있는 데이터 세트
3. 예제 데이터로는 : datasets.load_boston(), ~.load_breat_cancer(), ~.load_diabetes(), ~.load_digits(), ~.load_iris(), ~.make_classifications(), ~.make_blobs() 등이 있음.
4. fetch 계열의 명령은 데이터가 커서 패키지에 저장되어 있지 않고, 인터넷에 내려받아 사용함.

<데이터 세트의 딕셔너리로 저장된 키 의 의미>
1. data : 피처의 데이터 세트를 가리킴 ==> ndarray 타입
2. target : 분류 시 레이블 값, 회귀일 땐 숫자 결괏값 데이터 세트 ==> ndarray 타입
3. target_name : 개별 레이블의 이름을 나타냄 ==> list 타입
4. feature_names : 피처의 이름을 나타냄 ==> list 타입
5. DESCR : 데이터 세트에 대한 설명과 각 피처의 설명을 나타냄 ==> 스트링 타입

In [14]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data)) # 딕셔너리 형태를 가짐

<class 'sklearn.utils.Bunch'>


In [15]:
#딕셔너리 형태로 저장된 데이터 세트의 key 출력
keys = iris_data.keys()
print('붓꽃 데이터 세트의 키들:', keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


- 데이터 키는 피처들의 데이터 값을 가리킵니다.
- 데이터 세트가 딕셔너리 형태이기 때문에 피처 데이터 값을 추출하기 위해서는 '데이터세트.data' (혹은 데이터세트['data'] ) 를 이용하면 됨. (위의 코드에서 출력한 data, target, frame .. 등 모두)

In [19]:
print('\n feature_names 의 type:', type(iris_data.feature_names))
print('feature_names 의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names) # key 이기 때문에 딕셔너리.key 혹은 딕셔너리[key] 로 출력가능

print('\n target_names 의 type:', type(iris_data.target_names))
print('target_names 의 shape:', len(iris_data.target_names))
print(iris_data.target_names)

print('\n data 의 type:', type(iris_data.data))
print('data 의 shape:', iris_data.data.shape)
print(iris_data['data'])

print('\n target 의 type:', type(iris_data.target))
print('target 의 shape:', len(iris_data.target))
print(iris_data['target'])


 feature_names 의 type: <class 'list'>
feature_names 의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names 의 type: <class 'numpy.ndarray'>
target_names 의 shape: 3
['setosa' 'versicolor' 'virginica']

 data 의 type: <class 'numpy.ndarray'>
data 의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]


4. Model Selection 모듈 소개
- 사이킷런의 model_selection 모듈 : 학습 데이터와 테스트 데이터 세트를 분리하거나 교차 검증 분할 및 평가, 그리고 Estimator의 하이퍼 파라미터를 튜닝하기 위한 다양한 함수와 클래스를 제공

<학습 / 테스트 데이터 세트 분리 - train_test_split()>

In [20]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
#학습 수행
dt_clf.fit(train_data, train_label)

#학습 데이터 세트으로 예측 수행
pred=dt_clf.predict(train_data)
print('예측 정확도 :', accuracy_score(train_label, pred))

예측 정확도 : 1.0


In [ ]:
5. 데이터 전처리