# **Chapter1. 파이썬 기반의 머신러닝과 생태계 이해**
## 1. 머신러닝의 개념
- 머신러닝 : 데이터를 기반으로 패턴을 학습하고, 결과를 예측하는 알고리즘 기법
- 머신러닝의 분류
 1. 지도학습 : 분류, 회귀, 추천 시스템, 시각/음성감지/인지, 텍스트분석, NLP
 2. 비지도학습 : 클러스터링, 차원축소, 강화학습
## 2. 파이썬 머신러닝 생태계를 구성하는 주요 패키지
1. 머신러닝 패키지 : Scikit-Learn
2. 행렬/선형대수/통계 패키지 : Numpy, (Scipy)
3. 데이터 핸들링 : pandas
4. 시각화 : Matplotlib


In [ ]:
# 패키지 설지 확인
import numpy
import pandas
import matplotlib.pyplot
import seaborn
from sklearn.model_selection import train_test_split

## 3. 넘파이
- 넘파이 : 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지 이다.
- 루프를 사용하지 않고 대량 데이터의 배열 연산을 가능하게 하므로, 빠른 배열 연산 속도를 보장
- 파이썬 기반의 많은 과학과 공학 패키지가 넘파이에 의존

### 1) 넘파이 ndarray 개요

In [4]:
import numpy as np

- 넘파이의 기반 데이터 타입 : ndarray
- ndarray 를 이용해 다차원 배열을 쉽게 생성하고 다양한 연산 수행

#### array() 함수 ==> np.array([]) 로 사용
- array() 함수 : 파이썬의 리스트와 같은 인자를 입력받아 **ndarray 로 변환**
- ndarray.shape: ndarray 의 차원과 크기를 tuple (튜플) 형태로 나타냄.
- 생성된 ndarray 배열의 shape 변수는 ndarray 의 크기, 즉 행과 열의 수를 tuple 형태로 가지고 있음.

In [7]:
# 1차원 array / 3개 데이터 가지고 있음 / array1 의 shape 은 (3,)

array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [9]:
# 2차원 array / 2*3 (6개) 의 데이터를 가지고 있음
# array2의 shape 은 (2,3) 즉, 2개의 row와 3개의 column 을 가지고 있단 뜻.

array2=np.array([[1,2,3],
                 [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


In [10]:
# 2차원 array / 3개의 데이터 개수 / array3 의 shape 은 (1,3) 이다.
# array1 은 명백히 1차원 데이터임을 나타내기 위해 (3,) 형태로 나타냄.

array3=np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


- 주의 ) array1, array3 는 데이터 값은 동일하나, **차원이 다름**

In [11]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


### 2) ndarray 의 데이터 타입
- ndarray 내의 데이터값은 숫자 값, 문자열 값, 불 값 등이 모두 가능
- 숫자경우 : int형(8,16,32bit), unsigned int형(8,16,32bit), float형(16,32,64,128bit)
- ndarray 내 데이터 타입은 연산의 특성상 **같은 데이터 타입만 가능하다** ==> 즉 한개의 ndarry 객체에 int와 float 가 함께 있을 수 없다.
- ndarray 내의 데이터 타입은 dtype 속성으로 확인 가능


In [12]:
# list1 은 int 3개 data 가짐.

list1 =[1,2,3]
print(type(list1))

# list1 을 ndarray 타입으로 변경
array1=np.array(list1)
print(type(array1))

# .dtype => array 내 데이터 타입 알 수 있음. 여기서는 int 32
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [13]:
# 여러 데이터 타입이 섞여 있는 경우 ==> list2 는 int 와 string 이 섞여 있는 리스트.
# 이럴 경우 리스트를 ndarray 로 변경하면, 데이터 크기가 더 큰 데이터 타입으로 형 변환 일괄 적용

list2= [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype) # 숫자 1,2가 모두 문자열 값인 '1', '2' 로 변경 됨.

# 여러 데이터 타입이 섞여 있는 경우 ==> list3 는 int 와 float 가 섞여 있는 리스트
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype) # 1,2가 float64 형으로 변환됨

['1' '2' 'test'] <U11
[1. 2. 3.] float64


- astype() : 이 함수를 이용해서도 ndarray 내 데이터 값의 타입 변경 가능.
- astype() 에 인자로 원하는 타입을 문자열로 지정하면 됨.
- 이렇게 데이터 타입을 변경하는 경우 ==> 대용량 데이터의 ndarray 를 만들 때 메모리를 절약 가능
- ex) int 로 충분한 경우 데이터 타입이 float 라면 int형으로 바꿔 메모리 절약


In [14]:
# int 32 형 데이터를 float64로 변환

array_int = np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float, array_float.dtype)

# 다시 float64를 int32 로 변환
array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

# float 타입을 int 형으로 변경할 때, 당연히 소수점 이하는 없어짐.
array_float1 = np. array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### 3) ndarray 를 편리하게 생성하기 - arange, zeros, ones

- 특정 크기와 차원을 가진 ndarray 를 연속값이나, 0,1로 초기화 해 쉽게 생성할 경우
- arange(), zeros(), ones() 사용 ==> 쉽게 ndarray 생성

#### arange() 함수
- arange() 함수 : 파이썬 표준 함수인 range() 와 유사한 기능
- array 를 range() 로 표현
- 0 부터 (값-1) 까지의 값을 순차적으로 ndarray 데이터 값으로 변환해줌
- range 와 비슷하게 arange(초기값, 끝난값) 지정 가능

In [16]:
# arange() 는 [0 ~ 숫자-1] 까지의 값을 순차적으로 ndarray 데이터 값으로 변환

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape) # 결과를 보면 알 수 있듯이 1차원 값

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


#### zeros() 함수
- zeros() : 튜플 형태의 shape 값을 입력하면 모든 값을 0 으로 채운 해당 shape 을 가진 ndarray 를 반환
- ones() : zeros 와 비슷하게 1로 채운 shape 를 가진 ndarray 반환
- 둘 다 함수 인자로 dtype 을 정해주지 않으면, default 값으로 float64 의 데이터를 만듬


In [17]:
# zeros() ==> (3,2) 를 모두 0 으로 채움
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

# ones() ==> (3,2) 를 모두 1로 채움
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### 4) ndarray 의 차원과 크기를 변경하는 reshape()
#### reshape() 함수
- reshape() : ndarray 를 특정 차원 및 크기로 변환
- reshape() 은 지정된 사이즈로 변경이 불가능하면, 오류를 발생함. ex) (10, ) 데이터를 (4,3) shape으로 변환할 순 없다.
- 변환을 원하는 크기를 함수 인자로 부여하면 됨.

In [21]:
# 1차원 shape의 ndarray 인 array1
array1 = np.arange(10)  # array() 와 arange() 착각하지 말기!!!!
print('array1:\n', array1)

# array1을 2차원 ndarray 로 변환.
array2 = array1.reshape(2,5) # 2row, 5column
print('array2:\n', array2)

array3 = array1.reshape(5,2) # 5row, 2column
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


- tip) reshape() 함수에 -1 을 인자로 적용하면, 자동으로 값을 설정하여 원래 ndarray 와 호환되는 새로운 shape 로 변환해줌
- 물론 -1 을 사용하더라도, 호환될 수 없는 형태는 변환할 수 없다.
- ex) 10개의 1차원 데이터를 고정된 4개 칼럼을 가진 로우로는 변경 불가 ==> 에러
- -1 인자는 reshape(-1,1) 와 같은 형태로 자주 사용됨
- ** reshape(-1,1) ** 은 원본 ndarray 가 어떤 형태라도 2차원, 여러 row 를 가지되, 반드시 1개의 column 을 가진 ndarray 로 변환

In [23]:
# 고정된 5개 column 에 맞는 row 를 자동생성
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)

# 고정된 5개 row 에 맞는 column 를 자동생성
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [24]:
# reshape(-1,1) 을 사용해 3차원을 2차원으로 변경
# tolist() 함수 : 리스트를 자료형으로 만들 수 있다.

array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


### 5) 넘파이의 ndarray 의 데이터 세트 선택하기 - 인덱싱
1. 특정 데이터 추출
2. 슬라이싱 (slicing) : 연속된 인덱스 상의 ndarray 추출
3. 팬시 인덱싱 (fancy indexing)
4. 불린 인덱싱 (boolean indexing)

#### 단일 값 추출

In [25]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

# index 는 0부터 시작하므로, array1[2] 는 3번째, index 위치의 데이터 값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [26]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [27]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [ ]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값 :', array2d[0,0])
print('(row=0, col=1) index 가리키는 값 :', array2d[0,1])
print('(row=1, col=0) index 가리키는 값 :', array2d[1,0])
print('(row=2, col=2) index 가리키는 값 :', array2d[2,2])


#### 슬라이싱

In [28]:
array1 = np.arange(1,10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [29]:
array1 = np.arange(1,10)
array4= array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [31]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [ ]:
print(array2d[0])
print(array2d[1])

#### 팬시 언덱싱

In [33]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1], 2] => ', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2 =>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2 => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


#### 불린 인덱싱

In [34]:
array1d = np.arange(1,10)
# [] 안에 array1d > 5 boolean indexing 을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [ ]:
array1d > 5

In [35]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [ ]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

### 6) 행렬의 정렬 - sort()와 argsort()
#### 행렬의 정렬

In [37]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

#np. sort() 로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

#ndarray.sort() 로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [38]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬 :', sort_array1_desc)

내림차순으로 정렬 : [9 5 3 1]


In [39]:
array2d = np.array([[8,12],
                    [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis= 0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬 :\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬 :
 [[ 8 12]
 [ 1  7]]


#### 정렬된 행렬의 인덱스를 반환하기

In [ ]:
org_array= np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

In [40]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [42]:
import numpy as np

name_array = np.array(['Jone', 'Mike', 'Kate', 'Sarah', 'Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array 의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array 의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array 의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array 의 이름 출력: ['Jone' 'Kate' 'Samuel' 'Mike' 'Sarah']


### 7) 선형대수 연산 - 행렬 내적과 전치 행렬 구하기
#### 행렬 내적 (행렬 곱)

In [43]:
A = np.array( [[1,2,3],
               [4,5,6]])
B = np.array( [[7,8],
               [9,10],
               [11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n ', dot_product)

행렬 내적 결과:
  [[ 58  64]
 [139 154]]


#### 전치 행렬

In [ ]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpost(A)
print('A의 전치 행렬 : \n', transpose_mat)